### ISSUE TITLE
Buy Emblems

### ISSUE THREAD

**Issue by CurtisVonRubenhoff** [CurtisVonRubenhoff/PartyTime#1]
parent to #10
parent to #12
parent to #13

The party-goers need a way to spend their hard earned cash on some emblems.

- [ ] there's a space to buy emblems (#10)
- [ ] going past it brings up dialog to buy emblems (#12)
- [ ] buying one is reflected in cash/emblem count (#13)
