### ISSUE TITLE
Antagonist 

### ISSUE THREAD

**Issue by CurtisVonRubenhoff** [CurtisVonRubenhoff/PartyTime#6]
parent to #22
parent to #23
parent to #24
parent to  #25
parent to #26

This almost never ends well

- [ ] landing brings to Antagonist sequence #22 
- [ ] there are punishment options #23 
- [ ] punishment is chosen at random #24 
- [ ] if player has no coins, Antagonist rewards them with 30 cash #26 
- [ ] results are reflected in player stats afterwards #25

**Comment by CurtisVonRubenhoff** [comment]
will need design pass to consider punishments
