### ISSUE TITLE
Item Game

### ISSUE THREAD

**Issue by CurtisVonRubenhoff** [CurtisVonRubenhoff/PartyTime#8]
parent to #16
parent to #17
parent to #18
parent to #19

Get an item!! Or don't

- [ ] landing on space initiates item game dialog #19 
- [ ] question prompt appears #16 
- [ ] player can respond to question #17 
- [ ] answer is acknowledged and player is rewarded #18

**Comment by CurtisVonRubenhoff** [comment]
as with #5 the mini games don't need to exist yet. for now, item space will _only_ ask a question.
