### ISSUE TITLE
Main Menu

### ISSUE THREAD

**Issue by CurtisVonRubenhoff** [CurtisVonRubenhoff/PartyTime#9]
parent to #14
parent to #15

Lets someone actually start the game.

- [ ] displays the title
- [ ] has an options menu (#14)
- [ ] Has option to make new game (#15 )
- [ ] Quit
- [ ] parallaxvisions.com

**Comment by CurtisVonRubenhoff** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Main Menu](https://trello.com/c/Y54cYQnQ/1-main-menu)
